<!-- teste promise -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>

<script>

	function a(falhar) {

		return new Promise((resolve, reject) => {

			setTimeout(() => {

				if(falhar) {

					reject('PROMISE A FALHOU');
				} else {

					console.log('PROMISE A RESOLVIDA');
					resolve('DADO A');
				}

			}, 2000);
		});
	}

	function b(falhar) {

		return new Promise((resolve, reject) => {

			setTimeout(() => {

				if(falhar) {

					reject('PROMISE B FALHOU');
				} else {

					console.log('PROMISE B RESOLVIDA')
					resolve('DADO B');
				}

			}, 4000);
		});
	}

	function c(falhar) {

		return new Promise((resolve, reject) => {

			setTimeout(() => {

				if(falhar) {

					reject('PROMISE C FALHOU');
				} else {

					console.log('PROMISE C RESOLVIDA')
					resolve('DADO C');
				}

			}, 1000);
		});
	}

	// PARA TESTAR O ANINHAMENTO

	// a()
	// .then(dado => {
	// 	console.log(dado);
	// 	// O RETORNO DA PROMISE B ESTARÁ DISPONÍVEL NO PRÓXIMO THEN
	// 	return b();
	// })
	// .then(dado => {
	// 	console.log(dado);
	//
	// 	/* FORÇANDO A REJEIÇÃO DA PROMISE. TEM QUE IR DIRETO PARA O CATCH.
	// 	SE NÃO TIVESSE REJEITADO, O RETORNO DE C ESTARIA DISPONÍVEL NO PRÓXIMO THEN */
	// 	return c(true);
	// })
	// .then(dado => {
	// 	console.log(dado);
	// })
	// .catch(erro => console.log(erro));

	// PARA TESTAR O CONSUMO DE PROMISES EM PARALELO

	Promise.all([a(true), b(true), c()])
		.then(arrayComResultadoDasPromises => {
			// SE TODAS AS PROMISES ACONTECERAM COM SUCESSO LOGA ESSE CARA
			console.log(arrayComResultadoDasPromises)
		})
		.catch(erroDeAlgumaDasPromises => {
			// AQUI VAI LOGAR O PRIMEIRO ERRO QUE ENCONTRAR E ACABA A EXECUÇÃO
			console.log(erroDeAlgumaDasPromises)
		});

</script>
</body>